[package]
name = "rust-hello"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "rust-hello"
path = "src/client/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]